minor

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -60,6 +60,13 @@ jobs:
         run: |
     
          $env:VERSION_FRAGMENT > VERSION
+      - name: Validate version format
+        run: |
+          current_version=$(cat $VERSION_FILE_NAME)
+          if [[ ! $current_version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Invalid version format: $current_version"
+            exit 1
+          fi
       - name: Generate versions
         uses: HardNorth/github-version-generate@v1.3.0
         with:
